config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
   root 'recipes#index'

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :directions 
	has_many :ingredients
	belongs_to :user
	validates :title, :description, presence: true
	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@recipes = Recipe.all.order('created_at DESC')
	end

	def show
	end

	def new
		@recipe = Recipe.new
	end

	def create
	@recipe = Recipe.new(recipe_params) 
	@recipe.user = current_user
	
	@recipe.image = params[:file]
		if @recipe.save
			redirect_to recipe_path(@recipe), notice: "Successfully created new recipe "
		else
			render 'new'
		end

	end

	def edit 
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to recipe_path(@recipe), notice: "Successfully updated new recipe "
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.delete
		redirect_to root_path, notice: "Successfully deleted the recipe"
	end

	private

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id,:step, :_destroy])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!5
%html
	%head
		%title RecipeBox
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true 
		= csrf_meta_tags 

	%body
		%nav.navbar.navbar-default
			.container
				.navbar-brand=link_to 'RECIPE BOX', root_path
				%ul.nav.navbar-nav.navbar-right
					- if user_signed_in?
						%li
							= link_to 'New Recipe', new_recipe_path
						%li
							= link_to 'Sign Out', destroy_user_session_path, method: :delete
					- else
						%li
							= link_to 'Sign In', new_user_session_path
						%li
							= link_to 'Sign Up', new_user_registration_path


		.container
			- flash.each do |name, message|
				= content_tag :div, message, class: "alert alert-#{name}"
			
			= yield 

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: "form-control form-input"}
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default" 

app/views/recipes/_form.html.haml
= simple_form_for @recipe , html: {multipart: true} do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= pluralize(@recipe.errors.count, 'error')
				prevented this recipe from saving 
			%ul
				= @recipe.errors.full_messages.each do |message|
					%li= message
	.panel-body
		= f.input :title, input_html: { class: 'form-control'}
		= f.input :description, input_html: {class: 'form-control'}
		= f.input :image, input_html: {class: 'form-control'}
				
		.row
			.col-md-6
				%h2 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						=render 'direction_fields' , f: direction
					.links
						= link_to_add_association 'add direction', f, :directions, class: "btn btn-default add-button"
			.col-md-6
				%h2 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						=render 'ingredient_fields' , f: ingredient
					.links
						= link_to_add_association 'add ingredient', f, :ingredients, class: "btn btn-default add-button"


	= f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: "form-input form-control"}
		= link_to_remove_association "Remove", f, class: "form-button btn btn-default" 

app/views/recipes/edit.html.haml
%h2 Edit Recipe

= render :partial => 'form'

%br/

= link_to 'Back', root_path, class: "btn btn-default"

app/views/recipes/index.html.haml
%h3 All Recipes
- @recipes.each_slice(3) do |recipes|
	.row
	-recipes.each do |recipe|
		.col-md-4
			.recipe
				.image_wrapper 
					= image_tag (recipe.image_url)  unless recipe.image.nil?
				%h2
					= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h2 New Recipe
= render :partial => "form"

%br/

= link_to 'Back', root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag (@recipe.image_url), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.title	
				%p.description= @recipe.description
				%p
					Submitted by
					= @recipe.user.email	

	.row
		.col-md-6
			#directions
				%h2 Directions
				%ul
				- @recipe.directions.each do |direction|
					%li= direction.step
		.col-md-6
			#ingredients
				%h2 Ingredients
				%ul
				- @recipe.ingredients.each do |ingredient|
					%li= ingredient.name
	.row
		.col-md-12
			- if user_signed_in?
				=link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-primary" 
				=link_to 'Delete', @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" 
			=link_to 'Back', root_path, class: "btn btn-default"